// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAwmv3tXvd0WitOjJkYIxe2V0YDWi15tkE',
    appId: '1:1089681700120:web:9613192fbe1084ea589a6d',
    messagingSenderId: '1089681700120',
    projectId: 'firts-app-f7952',
    authDomain: 'firts-app-f7952.firebaseapp.com',
    databaseURL: 'https://firts-app-f7952-default-rtdb.firebaseio.com',
    storageBucket: 'firts-app-f7952.firebasestorage.app',
    measurementId: 'G-S233LW7VB8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD1i5gNx4JfbO0bZiZqCDDn3XZPN3nWyb0',
    appId: '1:1089681700120:android:0b696623b08d1bdf589a6d',
    messagingSenderId: '1089681700120',
    projectId: 'firts-app-f7952',
    databaseURL: 'https://firts-app-f7952-default-rtdb.firebaseio.com',
    storageBucket: 'firts-app-f7952.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCDzeJqv_q2fA9VeEtobH1UwLAYiB_SDEs',
    appId: '1:1089681700120:ios:6b14391aca4e8683589a6d',
    messagingSenderId: '1089681700120',
    projectId: 'firts-app-f7952',
    databaseURL: 'https://firts-app-f7952-default-rtdb.firebaseio.com',
    storageBucket: 'firts-app-f7952.firebasestorage.app',
    iosBundleId: 'com.example.fasumPab',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCDzeJqv_q2fA9VeEtobH1UwLAYiB_SDEs',
    appId: '1:1089681700120:ios:6b14391aca4e8683589a6d',
    messagingSenderId: '1089681700120',
    projectId: 'firts-app-f7952',
    databaseURL: 'https://firts-app-f7952-default-rtdb.firebaseio.com',
    storageBucket: 'firts-app-f7952.firebasestorage.app',
    iosBundleId: 'com.example.fasumPab',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAwmv3tXvd0WitOjJkYIxe2V0YDWi15tkE',
    appId: '1:1089681700120:web:a79feeb5c4e6d8fd589a6d',
    messagingSenderId: '1089681700120',
    projectId: 'firts-app-f7952',
    authDomain: 'firts-app-f7952.firebaseapp.com',
    databaseURL: 'https://firts-app-f7952-default-rtdb.firebaseio.com',
    storageBucket: 'firts-app-f7952.firebasestorage.app',
    measurementId: 'G-BGCV019FFT',
  );
}
