// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA57TcwtihPg0ls705Y33jgqnjLa9A1puA',
    appId: '1:603510617905:web:46e649ffd616bc54392210',
    messagingSenderId: '603510617905',
    projectId: 'fasum-1c2e7',
    authDomain: 'fasum-1c2e7.firebaseapp.com',
    storageBucket: 'fasum-1c2e7.firebasestorage.app',
    measurementId: 'G-VEGCZ4NFDV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBlEbToeeybZqlDxCIhxMs5h1pm1Nl8Rb4',
    appId: '1:603510617905:android:6eaccebf188a5228392210',
    messagingSenderId: '603510617905',
    projectId: 'fasum-1c2e7',
    storageBucket: 'fasum-1c2e7.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAcVMR96RbvDGC73XWrZy1Ja6gepLiHDFw',
    appId: '1:603510617905:ios:e0879de7b5dae3f6392210',
    messagingSenderId: '603510617905',
    projectId: 'fasum-1c2e7',
    storageBucket: 'fasum-1c2e7.firebasestorage.app',
    iosBundleId: 'com.example.fasumPab',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAcVMR96RbvDGC73XWrZy1Ja6gepLiHDFw',
    appId: '1:603510617905:ios:e0879de7b5dae3f6392210',
    messagingSenderId: '603510617905',
    projectId: 'fasum-1c2e7',
    storageBucket: 'fasum-1c2e7.firebasestorage.app',
    iosBundleId: 'com.example.fasumPab',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA57TcwtihPg0ls705Y33jgqnjLa9A1puA',
    appId: '1:603510617905:web:1b8d2fbf14733f73392210',
    messagingSenderId: '603510617905',
    projectId: 'fasum-1c2e7',
    authDomain: 'fasum-1c2e7.firebaseapp.com',
    storageBucket: 'fasum-1c2e7.firebasestorage.app',
    measurementId: 'G-9VDTXN1ZX4',
  );

}